### PR TITLE
Upgrade to version 3.3.3

### PR DESCRIPTION
**Pull request by mrterry**
This version fixes a security vulnerability in XML-RPC.

### CODE REVIEW

**Comment by sodre** [comment]
I will take care of it during the merge. I rather not delay the CI tests.

**Comment by mrterry** [comment]
The TravisCI job ran for "about 3 hours" then was canceled.  There doesn't appear to be any output.  Does this reflect a bad PR or the overloaded conda-forge build infrastructure?

**Comment by mrterry** [comment]
I can change the build number and let everything churn through the build pipeline again.

**Comment by sodre** [comment]
@mrterry please do that. If that still fails I will run the OS X tests locally.

**Comment by mrterry** [comment]
Thanks!

**Pull request merged**
