### PR TITLE
Runs out of the box configuration and init files.

### PR DESCRIPTION
**Pull request by sodre**
This PR is about:
 - Using PREFIX to properly render the sample configuration files
 - Ensuring running 'supervisord' runs out of the box in OS X and linux.

### CODE REVIEW

**Comment by sodre** [comment]
@kalefranz,

I finally fixed the build issues for macOS. Can you review this PR as soon as you get a chance? I did not add myself as a maintainer, but I am more than willing to put the effort in keeping this package up to date. 

Thanks!

**Comment by sodre** [comment]
@conda-forge/core @kalefranz 
Hi folks, I've had a PR pending for supervisor for a couple of weeks. Is there any chance that I can be added as a co-maintainer for this package?

Thanks!

**Comment by ocefpaf** [comment]
>  Is there any chance that I can be added as a co-maintainer for this package?

You can add yourself in this PR.

Ping @kalefranz for a review.

**Comment by sodre** [comment]
pinging @kalefranz for a review.

**Comment by sodre** [comment]
back to the drawing board. for some reason the service files were modified during commit.

**Pull request merged**
