### PR TITLE
Synchronize with AnacondaRecipes

### PR DESCRIPTION
**Pull request by sodre**

### CODE REVIEW

**Comment by sodre** [comment]
@nehaljwani, any chance that you merge your changes back? It would be great to keep this recipe in sync.

**Comment by nehaljwani** [comment]
I went through https://github.com/conda-forge/supervisor-feedstock/issues/10 but distribute is a legacy package. I think you should replace it with setuptools.

**Comment by nehaljwani** [comment]
Whoever has `add_pip_as_python_dependency: false` in their ~/.condarc or exported as an environment variable, will face that problem, otherwise setuptools is almost always present because of unvendored-pip ;-)

**Comment by sodre** [comment]
@jjhelmus thanks for simplifying the unit-tests. I synchronized this repo with AnacondaRecipes.

**Comment by jjhelmus** [comment]
> @jjhelmus thanks for simplifying the unit-tests. I synchronized this repo with AnacondaRecipes.

Awesome, thanks for pulling in the changes!

**Pull request merged**
