### PR TITLE
MNT: Re-rendered with conda-smithy 2.2.2

### PR DESCRIPTION
**Pull request by sodre**
I also added myself as a maintainer

### CODE REVIEW

**Comment by sodre** [comment]
@kalefranz this is ready to merge.
 
It is a straight MNT release update, update to the build script to use --single-version-externally-managed, and update meta.yaml to be conda-build 2.0 compatible.

I also added myself as co-maintainer since I know you are busy with the work at Continuum.

**Comment by sodre** [comment]
@conda-forge/core 
I think the maintenance scripts never added me as a co-maintainer to supervisor-feedstock (it has been more than 24 hrs). Can you add me manually?

**Comment by ocefpaf** [comment]
> Can you add me manually?

You may need to wait a little longer than 24 hours in some cases. Give it more time and, if the scripts does not add you, we'll try to debug this.

**Comment by sodre** [comment]
@ocefpaf 
Hi Filipe, it has been a week and the bot did not add me to supervisor-feedstock. Are you able to take a look at why?

Thanks

**Comment by ocefpaf** [comment]
> @ocefpaf 
Hi Filipe, it has been a week and the bot did not add me to supervisor-feedstock. Are you able to take a look at why?

It seems that the script finally worked. I see you listed at https://github.com/orgs/conda-forge/teams/supervisor

Let me know if you are all set @sodre.

**Comment by ocefpaf** [comment]
> @ocefpaf 
Hi Filipe, it has been a week and the bot did not add me to supervisor-feedstock. Are you able to take a look at why?

It seems that the script finally worked. I see you listed at https://github.com/orgs/conda-forge/teams/supervisor

Let me know if you are all set @sodre.

**Pull request merged**
